name: eduance
description: E-learning application with AR technology

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  date_range_picker:
    git:
      url: https://github.com/LempereurBenjamin/date_range_picker

dependencies:
  flutter:
    sdk: flutter
  fluro: ^2.0.3
  flutter_icons: ^1.1.0
  google_fonts: ^2.1.0
  auto_size_text: ^2.1.0
  animated_text_kit: ^4.2.1
  lottie: ^1.2.1
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1
  dio: ^4.0.1
  pin_code_fields: ^7.3.0
  flutter_dotenv: ^5.0.2
  snack: ^2.0.0
  badges: ^2.0.1
  firebase_storage: ^10.1.0
  firebase_core: ^1.10.0
  firebase_analytics: ^8.3.4
  image_picker:
  cached_network_image: ^3.1.0+1
  flutter_secure_storage: ^4.2.1
  circular_countdown: ^2.1.0
  timer_controller: ^0.1.0
  double_back_to_close: ^2.0.0
  carousel_slider: ^4.0.0
  progressive_image: ^2.0.0
  bubble_tab_indicator: "^0.1.5"




  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animation/
    - assets/images/comman/
    - assets/images/quiz/
    - assets/data/quiz/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
